### ISSUE TITLE
Separate tasks for css and js

### ISSUE THREAD

**Issue by vStone** [616slayer616/gradle-minify-plugin#2]
It is impossible to use minify with either only css or js files.

Workaround now is pointing one of them to some empty (but existing) non-project directory.

**Comment by 616slayer616** [comment]
This should be easy.
I have created a branch for it #3 
But I could not test it 

`Caused by: java.lang.NoClassDefFoundError: com/yahoo/platform/yui/compressor/CssCompressor`
It's weird I cannot even get version 1.0 to work locally. It only works if I use the published version

I'll see what happens when it's on the gradlePluginPortal.
